services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - /home/itaira/proj_containers/volumes/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "itairaest@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network
  app:
    build: .
    ports: 
      - "8501:8501"  # Correct: Host port 8501 maps to container port 8501
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
      driver: bridge